FROM carlonluca/vnc-desktop:questing-base
  
ENV DEBIAN_FRONTEND noninteractive  
RUN apt-get update \  
 && apt-get install -y kde-full plasma-session-x11 \
 && apt-get remove --purge plasma-workspace-wayland
  
RUN apt-get update \  
 && apt-get autoclean -y \  
 && apt-get autoremove -y \  
 && rm -rf /var/lib/apt/lists/*  
  
ADD startup.sh /  
ADD supervisord.conf /etc/supervisor/conf.d/  
ADD xvfb.sh /usr/local/bin/  
  
WORKDIR /root  
ENV SHELL=/bin/bash  
  
ENTRYPOINT ["/startup.sh"]  
